name: New Feature Report
description: File a new feature report.
title: "[Feature Request]: "
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new feature report!
  - type: textarea
    id: what-new-feat-info
    attributes:
      label: Describe the new feature
      description: A clear and concise description of the new feature.
      placeholder: "Adding clear information helps describe what new feature you would like added, if applicable add screenshots"
    validations:
      required: true
